directories:
    backups: /tmp/backups
    logs: /tmp/logs

cluster:
    name: myCluster
    backup-user: user
    backup-user-password: password

backup:
    interval: 1h
    max-backup-files: 10

mysqlrouter:
    http-addr: 127.0.0.1:8081

    basic-auth:
        user: user
        password: user

alerts:
    level: info
    telegram:
        bot-token: abracadabra
        chat-id: 34324
s3:
    bucket: innodb-backups
    endpoint: play.min.io
    access-key-id: Q3AM3UQ867SPQQA43P2F
    secret-access-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    use-ssl: true
