directories:
    backups: /tmp/backups
    logs:

cluster:
    name: myCluster
    backup-user: root
    backup-user-password:

backup:
    interval: 1m
    max-backup-files: 3

mysqlrouter:
    http-addr: 127.0.0.1:8081

    basic-auth:
        user: user
        password: user

alerts:
    level: info
    telegram:
        turn: off
        bot-token: 5019212361:AAHm4iiZh1AYWC7yBza-PpWRfDtWm17SzU4
        chat-id: 145073956
s3:
    bucket: innodb-backups
    endpoint: play.min.io
    access-key-id: Q3AM3UQ867SPQQA43P2F
    secret-access-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    use-ssl: true
